domains:
  - url: https://example.com         # The base URL for this domain
    seed_urls:                         # The entry point(s) for crawl jobs
      - https://example.com/

## Where to send the results. Possible values are console, file, or elasticsearch
output_sink: elasticsearch

## Elasticsearch index name to ingest crawl results into. Required if output_sink is elasticsearch
output_index: search-rag-example

## The maximum depth that Crawler will follow links to.
max_crawl_depth: 1
